spring:
  application:
    name: "deliveryI"
  messages:
    encoding: "UTF-8"

google:
  ai:
    api-key: ${GOOGLE_API_KEY}
    endpoint: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"